"""
image_data.py

Represents all image-related information generated by
the ImageLoader.

This object stores both the original image and the
working-resolution image used throughout preprocessing.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from data.image.image_metadata import ImageMetadata


@dataclass(slots=True)
class ImageData:
    """
    Complete image representation.

    Attributes
    ----------
    image
        Original RGB image.

    mask
        Original annotation mask.

    working_image
        Resized image used for preprocessing.

    working_mask
        Resized annotation mask.

    metadata
        Image metadata.
    """

    image: np.ndarray

    mask: np.ndarray

    working_image: np.ndarray

    working_mask: np.ndarray

    metadata: ImageMetadata

    @property
    def patient_id(self) -> str:
        return self.metadata.patient_id

    @property
    def image_shape(self):
        return self.image.shape

    @property
    def mask_shape(self):
        return self.mask.shape

    @property
    def working_image_shape(self):
        return self.working_image.shape

    @property
    def working_mask_shape(self):
        return self.working_mask.shape

    @property
    def width(self):
        return self.metadata.width

    @property
    def height(self):
        return self.metadata.height

    @property
    def working_width(self):
        return self.metadata.working_width

    @property
    def working_height(self):
        return self.metadata.working_height

    @property
    def scale_factor(self):
        return self.metadata.scale_factor

    @property
    def source_magnification(self):
        return self.metadata.source_magnification

    @property
    def target_magnification(self):
        return self.metadata.target_magnification