from __future__ import annotations

from utils.logger import get_logger

from methods.graph.neighborhood_finder import NeighborhoodFinder

from data.graph.patch_group import PatchGroup


class PatchGroupBuilder:
    """
    Builds graph-defined patch groups from a SpatialGraph.

    Each PatchGroup represents a local tissue neighborhood centered
    around a graph node. The builder itself is responsible only for
    orchestrating the grouping process. Neighborhood discovery is
    delegated to the NeighborhoodFinder.

    Notes
    -----
    This separation allows different grouping strategies
    (4-neighborhood, 8-neighborhood, k-hop, radius graph, etc.)
    to be introduced without modifying this class.
    """

    def __init__(
        self,
        config,
        logger=None,
    ) -> None:

        self.config = config
        self.logger = logger or get_logger(self.__class__.__name__)

        self._neighborhood_finder = NeighborhoodFinder(
            config=config,
            logger=self.logger,
        )

    def build(
        self,
        graph,
    ) -> list[PatchGroup]:
        """
        Construct patch groups from a spatial graph.

        Parameters
        ----------
        graph : SpatialGraph
            Graph generated by GraphBuilder.

        Returns
        -------
        list[PatchGroup]
            Collection of graph-defined patch groups.
        """

        self.logger.info("")
        self.logger.info("=" * 80)
        self.logger.info("BUILDING PATCH GROUPS")
        self.logger.info("=" * 80)

        patch_groups: list[PatchGroup] = []

        for group_id, center_node in enumerate(graph.nodes.values()):

            member_nodes = self._neighborhood_finder.find(
                center_node=center_node,
                graph=graph,
            )

            patch_group = PatchGroup(
                group_id=group_id,
                center_node=center_node,
                member_nodes=member_nodes,
            )

            patch_groups.append(
                patch_group,
            )

        self.logger.info(
            "Patch groups created : %d",
            len(patch_groups),
        )

        self.logger.info("=" * 80)

        return patch_groups