from __future__ import annotations

# from dataclasses import dataclass, field
from dataclasses import dataclass


from data.image.image_pair import ImagePair
from data.image.image_data import ImageData

from data.tissue.tissue_mask import TissueMask

# from data.patch.patch import Patch
from data.patch.patch_dataset import PatchDataset

from data.graph.graph import Graph

from data.dataset.dataset_manifest import DatasetManifest


@dataclass(slots=True)
class Patient:
    """
    Represents one patient throughout the complete
    preprocessing pipeline.

    Each preprocessing stage progressively enriches this
    object with the output generated by that stage.

    Dataset Discovery
            ↓
    Image Loading
            ↓
    Tissue Detection
            ↓
    Patch Extraction
            ↓
    Weak Label Generation
            ↓
    Graph Construction
            ↓
    Dataset Generation
    """

    # ==================================================
    # Patient Identity
    # ==================================================

    image_pair: ImagePair

    # ==================================================
    # Image Loading
    # ==================================================

    image_data: ImageData | None = None

    # ==================================================
    # Tissue Detection
    # ==================================================

    tissue_mask: TissueMask | None = None

    # ==================================================
    # Patch Extraction
    # ==================================================
    # NOTE:
    # This will later become:
    #
    # patch_dataset: PatchDataset | None = None
    #
    # Keeping a list temporarily until PatchDataset
    # is designed.
    # ==================================================

    # patches: list[Patch] = field(default_factory=list)
    patch_dataset: PatchDataset | None = None

    # ==================================================
    # Graph Construction
    # ==================================================

    graph: Graph | None = None

    # ==================================================
    # Dataset Generation
    # ==================================================

    dataset_manifest: DatasetManifest | None = None

    # ==================================================
    # Convenience Properties
    # ==================================================
    #
    # Patient Identity
    #
    # ==================================================

    @property
    def patient_id(self) -> str:
        return self.image_pair.patient_id

    @property
    def image_path(self):
        return self.image_pair.image_path

    @property
    def mask_path(self):
        return self.image_pair.mask_path

    @property
    def image_filename(self) -> str:
        return self.image_pair.image_filename

    @property
    def mask_filename(self) -> str:
        return self.image_pair.mask_filename

    # ==================================================
    # Image Loading
    # ==================================================

    @property
    def has_image(self) -> bool:
        return self.image_data is not None

    @property
    def image(self):
        if self.image_data is None:
            return None
        return self.image_data.image

    @property
    def mask(self):
        if self.image_data is None:
            return None
        return self.image_data.mask

    @property
    def working_image(self):
        if self.image_data is None:
            return None
        return self.image_data.working_image

    @property
    def working_mask(self):
        if self.image_data is None:
            return None
        return self.image_data.working_mask

    @property
    def metadata(self):
        if self.image_data is None:
            return None
        return self.image_data.metadata

    # ==================================================
    # Tissue Detection
    # ==================================================

    @property
    def has_tissue_mask(self) -> bool:
        """
        Returns True if tissue detection
        has been completed.
        """
        return self.tissue_mask is not None

    @property
    def tissue_binary_mask(self):
        """
        Returns the binary tissue mask.
        """
        if self.tissue_mask is None:
            return None

        return self.tissue_mask.mask

    @property
    def tissue_regions(self):
        """
        Returns all detected tissue regions.
        """
        if self.tissue_mask is None:
            return []

        return self.tissue_mask.regions

    @property
    def tissue_statistics(self):
        """
        Returns tissue statistics.
        """
        if self.tissue_mask is None:
            return None

        return self.tissue_mask.statistics

    @property
    def number_of_tissue_regions(self) -> int:
        """
        Returns the number of detected
        tissue regions.
        """
        if self.tissue_mask is None:
            return 0

        return self.tissue_mask.number_of_regions

    # ==================================================
    # Patch Extraction
    # ==================================================

    # @property
    # def has_patches(self) -> bool:
    #     return len(self.patches) > 0
    
    # ==================================================
    # Patch Extraction
    # ==================================================

    @property
    def patches(self):
        """
        Returns all extracted patches.
        """
        if self.patch_dataset is None:
            return []

        return self.patch_dataset.patches


    @property
    def number_of_patches(self) -> int:
        """
        Returns the number of extracted patches.
        """
        if self.patch_dataset is None:
            return 0

        return self.patch_dataset.number_of_patches


    @property
    def has_patches(self) -> bool:
        """
        Returns True if patches have been extracted.
        """
        return (
            self.patch_dataset is not None
            and self.patch_dataset.has_patches
        )
        

    # ==================================================
    # Graph Construction
    # ==================================================

    @property
    def has_graph(self) -> bool:
        return self.graph is not None

    # ==================================================
    # Dataset Generation
    # ==================================================

    @property
    def is_processed(self) -> bool:
        """
        Returns True when the complete
        preprocessing pipeline has finished.
        """
        return self.dataset_manifest is not None