"""
overlap_handler.py

Processes candidate patch coordinates generated by the
CoordinateGenerator.

The OverlapHandler does not generate coordinates.
Instead, it validates and organizes the generated coordinates
before patch generation.

Responsibilities
----------------
1. Validate overlap configuration.
2. Remove duplicate coordinates.
3. Sort coordinates.
4. Return a clean coordinate list.
"""

from typing import List

from data.patch.patch_coordinate import PatchCoordinate


class OverlapHandler:
    """
    Handles overlap-related post-processing of patch coordinates.
    """

    def __init__(
        self,
        patch_size: int,
        overlap: float,
    ):
        self.patch_size = patch_size
        self.overlap = overlap

    # ---------------------------------------------------------

    def process(
        self,
        coordinates: List[PatchCoordinate],
    ) -> List[PatchCoordinate]:
        """
        Process generated coordinates.

        Parameters
        ----------
        coordinates : List[PatchCoordinate]

        Returns
        -------
        List[PatchCoordinate]
        """

        self._validate_overlap()

        coordinates = self._remove_duplicates(
            coordinates
        )

        coordinates = self._sort_coordinates(
            coordinates
        )

        return coordinates

    # ---------------------------------------------------------

    def _validate_overlap(self):
        """
        Validate overlap percentage.
        """

        if self.overlap < 0.0:
            raise ValueError(
                "Overlap cannot be negative."
            )

        if self.overlap >= 1.0:
            raise ValueError(
                "Overlap must be less than 1."
            )

    # ---------------------------------------------------------

    def _remove_duplicates(
        self,
        coordinates: List[PatchCoordinate],
    ) -> List[PatchCoordinate]:
        """
        Remove duplicate coordinates.
        """

        unique = {}
        
        for coordinate in coordinates:

            key = (
                coordinate.x,
                coordinate.y,
            )

            if key not in unique:
                unique[key] = coordinate

        return list(unique.values())

    # ---------------------------------------------------------

    def _sort_coordinates(
        self,
        coordinates: List[PatchCoordinate],
    ) -> List[PatchCoordinate]:
        """
        Sort coordinates in scan order.
        """

        return sorted(
            coordinates,
            key=lambda c: (c.y, c.x)
        )